const { buildMarketplaceLazyBootstrapLines } = require('../marketplace-lazy-template.js');

function getClassInstallLines({ experimentalRuntimeToggleEnabled }) {
  return [
    '    translateTree(root) {',
    '      if (!root) return;',
    '      const perf = this._perf;',
    '      if (this._translatedSubtrees.has(root)) {',
    '        if (perf) perf.skippedTreeWalks += 1;',
    '        return;',
    '      }',
    '      const start = perf ? performance.now() : 0;',
    '      if (root.nodeType === Node.TEXT_NODE) {',
    '        this.translateNode(root);',
    '        if (perf) { perf.treeWalkCount += 1; perf.treeWalkTime += performance.now() - start; }',
    '        return;',
    '      }',
    '      if (root.nodeType === Node.ELEMENT_NODE) {',
    '        this.translateAttributes(root);',
    '        if (this.translateSpecialElement(root)) {',
    '          this._translatedSubtrees.add(root);',
    '          if (perf) { perf.treeWalkCount += 1; perf.treeWalkTime += performance.now() - start; }',
    '          return;',
    '        }',
    '        if (this.shouldSkipElement(root)) {',
    '          this._translatedSubtrees.add(root);',
    '          if (perf) { perf.treeWalkCount += 1; perf.treeWalkTime += performance.now() - start; }',
    '          return;',
    '        }',
    '      }',
    '      const hasIdle = typeof requestIdleCallback === "function";',
    '      const forceSync = this.shouldSyncTranslateScope(root);',
    '      if (!hasIdle || this._pendingAttributeElements || forceSync) {',
    '        this._chunkedTreeWalk(root, null);',
    '        this._chunkedAttributeWalk(root, null);',
    '        this._translatedSubtrees.add(root);',
    '        if (perf) { perf.treeWalkCount += 1; perf.treeWalkTime += performance.now() - start; }',
    '        return;',
    '      }',
    '      const doChunked = (deadline) => {',
    '        let done = true;',
    '        if (!this._treeWalkDone) {',
    '          this._treeWalkDone = this._chunkedTreeWalk(root, deadline);',
    '          done = this._treeWalkDone;',
    '        }',
    '        if (this._treeWalkDone && !this._attributeWalkDone) {',
    '          this._attributeWalkDone = this._chunkedAttributeWalk(root, deadline);',
    '          done = this._attributeWalkDone;',
    '        }',
    '        if (!done) {',
    '          requestIdleCallback(doChunked, { timeout: 200 });',
    '        } else {',
    '          this._treeWalkDone = false;',
    '          this._attributeWalkDone = false;',
    '          this._translatedSubtrees.add(root);',
    '          if (perf) { perf.treeWalkCount += 1; perf.treeWalkTime += performance.now() - start; }',
    '        }',
    '      };',
    '      this._treeWalkDone = false;',
    '      this._attributeWalkDone = false;',
    '      requestIdleCallback(doChunked, { timeout: 200 });',
    '    }',
    '    _scheduleFlush() {',
    '      if (this._flushTimer) return;',
    '      this._flushTimer = window.setTimeout(() => this._flushMutations(), 16);',
    '    }',
    '    _flushMutations() {',
    '      this._flushTimer = null;',
    '      if (!this._enabled) { this._pendingMutations = []; return; }',
    '      if (this._isFlushing) return;',
    '      this._isFlushing = true;',
    '      const perf = this._perf;',
    '      const start = perf ? performance.now() : 0;',
    '      try {',
    '        const mutations = this._pendingMutations;',
    '        this._pendingMutations = [];',
    '        const addedElements = [];',
    '        const segmentedTipRoots = new Set();',
    '        for (const mutation of mutations) {',
    '          mutation.addedNodes.forEach((node) => {',
    '            const specialRoot = this.findSegmentedTipRoot(node);',
    '            if (specialRoot) {',
    '              this._translatedSubtrees.delete(specialRoot);',
    '              segmentedTipRoots.add(specialRoot);',
    '              return;',
    '            }',
    '            if (node.nodeType === Node.TEXT_NODE) {',
    '              this.translateNode(node);',
    '              this._invalidateSubtree(node.parentElement);',
    '            } else if (node.nodeType === Node.ELEMENT_NODE) {',
    '              addedElements.push(node);',
    '              this._invalidateSubtree(node);',
    '            }',
    '          });',
    '          if (mutation.type === "characterData") {',
    '            const specialRoot = this.findSegmentedTipRoot(mutation.target);',
    '            if (specialRoot) {',
    '              this._translatedSubtrees.delete(specialRoot);',
    '              segmentedTipRoots.add(specialRoot);',
    '            } else {',
    '              this.translateNode(mutation.target);',
    '              this._invalidateSubtree(mutation.target.parentElement);',
    '            }',
    '          }',
    '          if (mutation.type === "attributes" && mutation.target) {',
    '            this.translateAttributes(mutation.target);',
    '            this._invalidateSubtree(mutation.target);',
    '          }',
    '        }',
    '        segmentedTipRoots.forEach((specialRoot) => this.translateSpecialElement(specialRoot));',
    '        for (let i = 0; i < addedElements.length; i++) {',
    '          const element = addedElements[i];',
    '          this.translateAttributes(element);',
    '          if (!this._pendingIdleRoots.has(element)) {',
    '            this._pendingIdleRoots.add(element);',
    '            this._idleQueue.push({ type: "translateTree", root: element });',
    '          }',
    '          if (element.tagName === "IFRAME") {',
    '            this.bindFrame(element);',
    '          }',
    '          if (element.shadowRoot) {',
    '            if (!this._pendingIdleRoots.has(element.shadowRoot)) {',
    '              this._pendingIdleRoots.add(element.shadowRoot);',
    '              this._idleQueue.push({ type: "translateTree", root: element.shadowRoot });',
    '              this._idleQueue.push({ type: "observeRoot", root: element.shadowRoot });',
    '            }',
    '          }',
    '        }',
    '        if (this._idleQueue.length > 0) this._scheduleIdleWork();',
    '      } finally {',
    '        this._isFlushing = false;',
    '        if (perf) { perf.mutationBatchCount += 1; perf.mutationBatchTime += performance.now() - start; }',
    '      }',
    '    }',
    '    observeRoot(root) {',
    '      if (!root || root.__cursorZhObserver) return;',
    '      const observer = new MutationObserver((mutations) => {',
    '        for (const mutation of mutations) {',
    '          this._pendingMutations.push(mutation);',
    '        }',
    '        this._scheduleFlush();',
    '      });',
    '      observer.observe(root, {',
    '        subtree: true,',
    '        childList: true,',
    '        characterData: true,',
    '        attributes: true,',
    '        attributeFilter: ["title", "aria-label", "aria-description", "placeholder"]',
    '      });',
    '      root.__cursorZhObserver = observer;',
    '    }',
    '    observeScopedRoots(root) {',
    '      const scopeRoots = this.collectScopeRoots(root);',
    '      const shouldStageRoot = Boolean(',
    '        root &&',
    '        (root.nodeType === Node.ELEMENT_NODE || root.nodeType === Node.DOCUMENT_FRAGMENT_NODE) &&',
    '        !this.hasScopedObservation()',
    '      );',
    '      if (shouldStageRoot) this._stageRootForTranslation(root);',
    '      if (scopeRoots.length === 0) return;',
    '      for (let i = 0; i < scopeRoots.length; i++) {',
    '        const scopeRoot = scopeRoots[i];',
    '        this.translateTree(scopeRoot);',
    '        this.observeRoot(scopeRoot);',
    '        this.observeExistingShadowRoots(scopeRoot);',
    '        this.observeExistingFrames(scopeRoot);',
    '      }',
    '    }',
    '    _stagedRoots = [];',
    '    _stagedTimer = null;',
    '    _isStagedTranslating = false;',
    '    _stageRootForTranslation(root) {',
    '      if (!root) return;',
    '      if (this._translatedSubtrees.has(root)) return;',
    '      if (this._stagedRootSet.has(root)) return;',
    '      this._stagedRootSet.add(root);',
    '      this._stagedRoots.push(root);',
    '      if (this._stagedTimer) return;',
    '      this._stagedTimer = window.setTimeout(() => this._flushStagedRoots(), 100);',
    '    }',
    '    _flushStagedRoots() {',
    '      this._stagedTimer = null;',
    '      if (this._isStagedTranslating) {',
    '        this._stagedTimer = window.setTimeout(() => this._flushStagedRoots(), 100);',
    '        return;',
    '      }',
    '      this._isStagedTranslating = true;',
    '      const batchSize = 3;',
    '      let processed = 0;',
    '      const flushBatch = () => {',
    '        while (processed < batchSize && this._stagedRoots.length > 0) {',
    '          const root = this._stagedRoots.shift();',
    '          if (root) this._stagedRootSet.delete(root);',
    '          if (root && !this._translatedSubtrees.has(root)) {',
    '            this.translateTree(root);',
    '          }',
    '          processed += 1;',
    '        }',
    '        if (this._stagedRoots.length > 0) {',
    '          window.setTimeout(() => {',
    '            processed = 0;',
    '            flushBatch();',
    '          }, 50);',
    '        } else {',
    '          this._isStagedTranslating = false;',
    '        }',
    '      };',
    '      flushBatch();',
    '    }',
    '    observeExistingShadowRoots(root) {',
    '      if (!root || !root.querySelectorAll) return;',
    '      const elements = root.querySelectorAll("*");',
    '      for (let i = 0; i < elements.length; i++) {',
    '        const element = elements[i];',
    '        if (!element.shadowRoot) continue;',
    '        this.translateTree(element.shadowRoot);',
    '        this.observeRoot(element.shadowRoot);',
    '      }',
    '    }',
    '    bindFrame(frame) {',
    '      if (!frame || frame.__cursorZhFrameBound) return;',
    '      const translateFrame = () => {',
    '        try {',
    '          const doc = frame.contentDocument;',
    '          if (!doc) return;',
    '          const root = doc.documentElement || doc.body || doc;',
    '          this.translateTree(root);',
    '          if (doc.documentElement) this.observeDiscoveryRoot(doc.documentElement);',
    '        } catch {}',
    '      };',
    '      frame.addEventListener("load", translateFrame);',
    '      frame.__cursorZhFrameBound = true;',
    '      translateFrame();',
    '    }',
    '    observeExistingFrames(root) {',
    '      if (!root || !root.querySelectorAll) return;',
    '      const frames = root.querySelectorAll("iframe");',
    '      for (let i = 0; i < frames.length; i++) {',
    '        this.bindFrame(frames[i]);',
    '      }',
    '    }',
    '    _scheduleDiscoveryFlush() {',
    '      if (this._discoveryFlushTimer) return;',
    '      this._discoveryFlushTimer = window.setTimeout(() => this._flushDiscoveryMutations(), 16);',
    '    }',
    '    _flushDiscoveryMutations() {',
    '      this._discoveryFlushTimer = null;',
    '      if (!this._enabled) { this._pendingDiscoveryMutations = []; return; }',
    '      if (this._isDiscoveryFlushing) return;',
    '      this._isDiscoveryFlushing = true;',
    '      try {',
    '        const mutations = this._pendingDiscoveryMutations;',
    '        this._pendingDiscoveryMutations = [];',
    '        const addedElements = [];',
    '        for (const mutation of mutations) {',
    '          mutation.addedNodes.forEach((node) => {',
    '            if (node.nodeType === Node.TEXT_NODE) {',
    '              this.translateNode(node);',
    '            } else if (node.nodeType === Node.ELEMENT_NODE) {',
    '              addedElements.push(node);',
    '            }',
    '          });',
    '          if (mutation.type === "attributes" && mutation.target) {',
    '            this.translateAttributes(mutation.target);',
    '          }',
    '        }',
    '        for (const node of addedElements) {',
    '          this.translateAttributes(node);',
    '          this.observeScopedRoots(node);',
    '          if (this.shortExactTextFallback) {',
    '            const fallbackText = (node.textContent || "").replace(/\\s+/g, " ").trim();',
    '            if (fallbackText && fallbackText.length <= 220) {',
    '              const fallbackRoot = node;',
    '              this.runShortExactTextFallback(fallbackRoot);',
    '            }',
    '          }',
    '          if (node.shadowRoot) {',
    '            this.translateTree(node.shadowRoot);',
    '            this.observeRoot(node.shadowRoot);',
    '          }',
    '          if (node.tagName === "IFRAME") {',
    '            this.bindFrame(node);',
    '          }',
    '        }',
    '      } finally {',
    '        this._isDiscoveryFlushing = false;',
    '      }',
    '    }',
    '    observeDiscoveryRoot(root) {',
    '      if (!root || root.__cursorZhDiscoveryObserver) return;',
    '      this._pendingDiscoveryMutations = [];',
    '      this._discoveryFlushTimer = null;',
    '      this._isDiscoveryFlushing = false;',
    '      const observer = new MutationObserver((mutations) => {',
    '        for (const mutation of mutations) {',
    '          let handledSync = false;',
    '          if (mutation.type === "childList") {',
    '            mutation.addedNodes.forEach((node) => {',
    '              if (node && node.nodeType === Node.ELEMENT_NODE) {',
    '                this.observeScopedRoots(node);',
    '                handledSync = true;',
    '              }',
    '            });',
    '          }',
    '          if (!handledSync) {',
    '            this._pendingDiscoveryMutations.push(mutation);',
    '          }',
    '        }',
    '        if (this._pendingDiscoveryMutations.length > 0) {',
    '          this._scheduleDiscoveryFlush();',
    '        }',
    '      });',
    '      observer.observe(root, {',
    '        subtree: true,',
    '        childList: true,',
    '        attributes: Boolean(translationMetadata.runtimeConfig.observeDiscoveryAttributes),',
    '        attributeFilter: Boolean(translationMetadata.runtimeConfig.observeDiscoveryAttributes)',
    '          ? ["title", "aria-label", "aria-description", "placeholder"]',
    '          : undefined',
    '      });',
    '      root.__cursorZhDiscoveryObserver = observer;',
    '    }',
    '    installShadowObserver() {',
    '      if (typeof Element === "undefined") return;',
    '      const proto = Element.prototype;',
    '      if (!proto || proto.__cursorZhAttachShadowPatched) return;',
    '      const originalAttachShadow = proto.attachShadow;',
    '      if (typeof originalAttachShadow !== "function") return;',
    '      const translator = this;',
    '      proto.attachShadow = function patchedAttachShadow(init) {',
    '        const shadowRoot = originalAttachShadow.call(this, init);',
    '        queueMicrotask(() => {',
    '          if (!translator.isScopeContainer(this) && !translator.collectScopeRoots(shadowRoot).length) return;',
    '          translator.translateTree(shadowRoot);',
    '          translator.observeRoot(shadowRoot);',
    '        });',
    '        return shadowRoot;',
    '      };',
    '      proto.__cursorZhAttachShadowPatched = true;',
    '    }',
    '    install() {',
    '      const run = () => {',
    '        const documentRoot = document.body || document.documentElement;',
    '        if (this.stageDocumentRoot && documentRoot) this._stageRootForTranslation(documentRoot);',
    '        if (this.shortExactTextFallback && documentRoot) {',
    '          const exactFallbackRoot = documentRoot;',
    '          this.runShortExactTextFallback(exactFallbackRoot);',
    '        }',
    '        const scopeRoots = this.collectScopeRoots(document);',
    '        for (let i = 0; i < scopeRoots.length; i++) {',
    '          this._stageRootForTranslation(scopeRoots[i]);',
    '          this.observeRoot(scopeRoots[i]);',
    '          this.observeExistingShadowRoots(scopeRoots[i]);',
    '          this.observeExistingFrames(scopeRoots[i]);',
    '        }',
    '      };',
    '      const periodicScan = () => {',
    '        run();',
    '      };',
    '      this.installShadowObserver();',
    '      if (document.readyState === "loading") {',
    '        document.addEventListener("DOMContentLoaded", periodicScan, { once: true });',
    '      } else {',
    '        periodicScan();',
    '      }',
    '      const rescanDelays = Array.isArray(translationMetadata.runtimeConfig.rescanDelaysMs)',
    '        ? translationMetadata.runtimeConfig.rescanDelaysMs',
    '        : [];',
    '      rescanDelays.forEach((delay) => {',
    '        if (!Number.isFinite(delay) || delay < 0) return;',
    '        window.setTimeout(() => periodicScan(), delay);',
    '      });',
    '      const startObserver = () => {',
    '        this.observeDiscoveryRoot(document.documentElement);',
    '        if (this._stagedRoots.length > 0 && !this._stagedTimer) {',
    '          this._stagedTimer = window.setTimeout(() => this._flushStagedRoots(), 100);',
    '        }',
    '      };',
    '      if (document.documentElement) startObserver();',
    '      else document.addEventListener("DOMContentLoaded", startObserver, { once: true });',
    '      window.__cursorZhRuntime = this;',
    '      window.__cursorZhMetadata = translationMetadata;',
    ...(experimentalRuntimeToggleEnabled
      ? [
          '      Object.defineProperty(window, "__cursorZhEnabled", {',
          '        get() { return window.__cursorZhRuntime ? window.__cursorZhRuntime.enabled : true; },',
          '        set(value) { if (window.__cursorZhRuntime) window.__cursorZhRuntime.enabled = value; },',
          '      });',
        ]
      : []),
    ...(experimentalRuntimeToggleEnabled ? ['      this._startTogglePolling();'] : []),
    '    }',
    '  }',
    '  new TextTranslator(translationMappings, translationMetadata.runtimeConfig || {}).install();',
    ...buildMarketplaceLazyBootstrapLines(),
    '})();',
  ];
}

module.exports = { getClassInstallLines };
