function getClassCoreLines() {
  return [
    '    _buildExactMap() {',
    '      for (let i = 0; i < this.entries.length; i++) {',
    '        const entry = this.entries[i];',
    '        if (!entry || !entry.originalText) continue;',
    '        const hasScope = (Array.isArray(entry.scopeSelectors) && entry.scopeSelectors.length > 0)',
    '          || (Array.isArray(entry.scopeContainsText) && entry.scopeContainsText.length > 0);',
    '        if (hasScope || entry.searchType !== "exact") continue;',
    '        if (!this._exactMap.has(entry.originalText)) {',
    '          this._exactMap.set(entry.originalText, entry.changeText);',
    '        }',
    '      }',
    '    }',
    '    _precomputeScopeHints() {',
    '      for (let i = 0; i < this.entries.length; i++) {',
    '        const entry = this.entries[i];',
    '        if (!entry || !Array.isArray(entry.scopeContainsText)) continue;',
    '        entry.__normalizedHints = entry.scopeContainsText.map((h) => this.normalizeText(h));',
    '      }',
    '    }',
    '    _getTextHash(text) {',
    '      let h = 0;',
    '      for (let i = 0; i < text.length; i++) {',
    '        h = ((h << 5) - h) + text.charCodeAt(i);',
    '        h |= 0;',
    '      }',
    '      return h;',
    '    }',
    '    _scheduleIdleWork() {',
    '      if (this._idleTimer) return;',
    '      this._idleTimer = window.setTimeout(() => this._processIdleQueue(), 0);',
    '    }',
    '    _processIdleQueue() {',
    '      this._idleTimer = null;',
    '      let queue = this._idleQueue;',
    '      this._idleQueue = [];',
    '      const perf = this._perf;',
    '      if (perf) { perf.idleQueueDepth = Math.max(perf.idleQueueDepth, queue.length); }',
    '      const treeTasks = [];',
    '      const otherTasks = [];',
    '      for (let i = 0; i < queue.length; i++) {',
    '        const task = queue[i];',
    '        if (task.type === "translateTree") {',
    '          treeTasks.push(task);',
    '        } else {',
    '          otherTasks.push(task);',
    '        }',
    '      }',
    '      const merged = [];',
    '      for (let i = 0; i < treeTasks.length; i++) {',
    '        const a = treeTasks[i];',
    '        if (!a) continue;',
    '        let contained = false;',
    '        for (let j = 0; j < treeTasks.length; j++) {',
    '          if (i === j || !treeTasks[j]) continue;',
    '          const b = treeTasks[j];',
    '          try {',
    '            if (a.root !== b.root && a.root.closest && a.root.closest(b.root)) {',
    '              contained = true;',
    '              break;',
    '            }',
    '          } catch {}',
    '        }',
    '        if (!contained) merged.push(a);',
    '        else if (perf) perf.idleQueueDeduped += 1;',
    '      }',
    '      queue = merged.concat(otherTasks);',
    '      for (let i = 0; i < queue.length; i++) {',
    '        const task = queue[i];',
    '        if (task.type === "translateTree") {',
    '          this._pendingIdleRoots.delete(task.root);',
    '          this.translateTree(task.root);',
    '        } else if (task.type === "observeRoot") {',
    '          this.observeRoot(task.root);',
    '        }',
    '        if (perf) perf.idleQueueProcessed += 1;',
    '      }',
    '    }',
    '    normalizeText(text) {',
    '      return String(text || "")',
    '        .replace(/\\u2026/g, "...")',
    '        .replace(/\\.{3,}/g, "...")',
    '        .replace(/&&/g, "")',
    '        .replace(/&/g, "")',
    '        .replace(/\\s+/g, " ")',
    '        .trim()',
    '        .toLowerCase();',
    '    }',
    '    shouldSkipElement(element) {',
      '      if (!element || element.nodeType !== Node.ELEMENT_NODE) return false;',
      '      try {',
      '        return Boolean(element.closest(this.skipSelector));',
      '      } catch {',
      '        return false;',
      '      }',
      '    }',
    '    matchesAnySelector(element, selectors) {',
    '      if (!element || element.nodeType !== Node.ELEMENT_NODE) return false;',
    '      if (!Array.isArray(selectors) || selectors.length === 0) return false;',
    '      return selectors.some((selector) => {',
    '        try {',
    '          return Boolean(element.matches(selector) || element.closest(selector));',
    '        } catch {',
    '          return false;',
    '        }',
    '      });',
    '    }',
    '    _getRegex(pattern, flags) {',
    '      const key = pattern + "\0" + flags;',
    '      let cached = this._regexCache.get(key);',
    '      if (!cached) {',
    '        cached = new RegExp(pattern, flags);',
    '        this._regexCache.set(key, cached);',
    '      }',
    '      return cached;',
    '    }',
    '    matchesScope(entry, element) {',
    '      const hasScopeSelectors = Array.isArray(entry.scopeSelectors) && entry.scopeSelectors.length > 0;',
    '      const hasScopeHints = Array.isArray(entry.scopeContainsText) && entry.scopeContainsText.length > 0;',
    '      if (!hasScopeSelectors && !hasScopeHints) return true;',
    '      if (!element || element.nodeType !== Node.ELEMENT_NODE) return false;',
    '      const cacheKey = entry.originalText + "\0" + (entry.searchType || "exact") + "\0" + (element.tagName || "");',
    '      const cached = this._scopeCache.get(cacheKey);',
    '      if (cached !== undefined) {',
    '        if (this._perf) this._perf.scopeCacheHits += 1;',
    '        return cached;',
    '      }',
    '      if (this._perf) this._perf.scopeChecks += 1;',
    '      let result = false;',
    '      if (hasScopeSelectors) {',
    '        try {',
    '          if (element.closest(entry.scopeSelectors.join(","))) { result = true; }',
    '        } catch {}',
    '      }',
    '      if (!result && hasScopeHints) {',
    '        let current = element;',
    '        for (let depth = 0; current && depth < 6; depth += 1, current = current.parentElement) {',
    '          const scopeText = this.normalizeText(current.textContent || "");',
    '          if (!scopeText) continue;',
    '          const hints = entry.__normalizedHints || entry.scopeContainsText;',
    '          if (hints.some((hint) => scopeText.includes(hint))) {',
    '            result = true;',
    '            break;',
    '          }',
    '        }',
    '      }',
    '      if (this._scopeCache.size >= this._scopeCacheLimit) {',
    '        const firstKey = this._scopeCache.keys().next().value;',
    '        this._scopeCache.delete(firstKey);',
    '      }',
    '      this._scopeCache.set(cacheKey, result);',
    '      this._scopeCacheWrites += 1;',
    '      if (this._scopeCacheWrites >= 100) {',
    '        this._scopeCacheWrites = 0;',
    '        this._adjustScopeCache();',
    '      }',
    '      return result;',
    '    }',
    '    _invalidateSubtree(element) {',
    '      let current = element;',
    '      while (current) {',
    '        if (this._translatedSubtrees.has(current)) {',
    '          this._translatedSubtrees.delete(current);',
    '          break;',
    '        }',
    '        current = current.parentElement;',
    '      }',
    '    }',
    '    _adjustScopeCache() {',
    '      const perf = this._perf;',
    '      if (!perf || perf.scopeChecks < 500) return;',
    '      const ratio = perf.scopeCacheHits / perf.scopeChecks;',
    '      if (ratio > 0.85 && this._scopeCacheLimit < 800) {',
    '        this._scopeCacheLimit += 50;',
    '      } else if (ratio < 0.3 && this._scopeCacheLimit > 50) {',
    '        this._scopeCacheLimit -= 50;',
    '      }',
    '      perf.scopeChecks = 0;',
    '      perf.scopeCacheHits = 0;',
    '    }',
    '    isScopeContainer(element) {',
    '      if (!element || element.nodeType !== Node.ELEMENT_NODE) return false;',
    '      if (!Array.isArray(this.observeScopeSelectors) || this.observeScopeSelectors.length === 0) return true;',
    '      return this.matchesAnySelector(element, this.observeScopeSelectors);',
    '    }',
    '    hasScopedObservation() {',
    '      return Array.isArray(this.observeScopeSelectors) && this.observeScopeSelectors.length > 0;',
    '    }',
    '    isSegmentedTipElement(element) {',
    '      if (!element || element.nodeType !== Node.ELEMENT_NODE) return false;',
    '      try {',
    '        return Boolean(element.matches(".glass-empty-state-rotating-tips__text"));',
    '      } catch {',
    '        return false;',
    '      }',
    '    }',
    '    findSegmentedTipRoot(node) {',
    '      if (!node) return null;',
    '      const element = node.nodeType === Node.ELEMENT_NODE ? node : node.parentElement;',
    '      if (!element || element.nodeType !== Node.ELEMENT_NODE) return null;',
    '      if (this.isSegmentedTipElement(element)) return element;',
    '      try {',
    '        return element.closest ? element.closest(".glass-empty-state-rotating-tips__text") : null;',
    '      } catch {',
    '        return null;',
    '      }',
    '    }',
    '    _renderTipContent(text) {',
    '      const fragment = document.createDocumentFragment();',
    '      const wrapper = document.createElement("span");',
    '      wrapper.className = "cursor-zh-tip-inline";',
    '      wrapper.style.display = "block";',
    '      wrapper.style.width = "100%";',
    '      wrapper.style.maxWidth = "100%";',
    '      wrapper.style.whiteSpace = "normal";',
    '      wrapper.style.textAlign = "center";',
    '      wrapper.style.lineHeight = "inherit";',
    '      const parts = String(text || "").split(/(\\s+)/);',
    '      for (let i = 0; i < parts.length; i++) {',
    '        const part = parts[i];',
    '        if (!part) continue;',
    '        if (/^\\s+$/.test(part)) {',
    '          wrapper.appendChild(document.createTextNode(part));',
    '          continue;',
    '        }',
    '        if (part.startsWith("/") || part.startsWith("@")) {',
    '          const chip = document.createElement("span");',
    '          chip.className = "glass-empty-state-rotating-tips__chip";',
    '          chip.textContent = part;',
    '          wrapper.appendChild(chip);',
    '          continue;',
    '        }',
    '        wrapper.appendChild(document.createTextNode(part));',
    '      }',
    '      fragment.appendChild(wrapper);',
    '      return fragment;',
    '    }',
    '    translateSpecialElement(element) {',
    '      if (!this._enabled) return false;',
    '      if (!element || element.nodeType !== Node.ELEMENT_NODE) return false;',
    '      if (this.shouldSkipElement(element)) return false;',
    '      if (!this.isSegmentedTipElement(element)) return false;',
    '      const text = element.textContent || "";',
    '      if (!text || text.length > 500) return false;',
    '      const translated = this.translateTextForElement(text, element);',
    '      if (translated === text) return false;',
    '      this._saveOriginalText(element, text);',
    '      while (element.firstChild) element.removeChild(element.firstChild);',
    '      element.appendChild(this._renderTipContent(translated));',
    '      return true;',
    '    }',
    '    translateText(text) {',
      '      return this.translateTextForElement(text, null);',
    '    }',
    '    translateTextForElement(text, element) {',
    '      if (typeof text !== "string" || text.length === 0) return text;',
    '      const perf = this._perf;',
    '      const start = perf ? performance.now() : 0;',
    '      let current = text;',
    '      const trimmed = current.trim();',
    '      const fast = this._exactMap.get(trimmed);',
    '      if (fast !== undefined) {',
    '        current = fast;',
    '      } else {',
    '        for (const entry of this.entries) {',
    '          if (!entry || !entry.originalText) continue;',
    '          if (!this.matchesScope(entry, element || null)) continue;',
    '          if (entry.searchType === "exact") {',
    '            if (trimmed === entry.originalText) current = entry.changeText;',
    '          } else if (entry.searchType === "normalizedExact") {',
    '            if (this.normalizeText(current) === this.normalizeText(entry.originalText)) current = entry.changeText;',
    '          } else if (entry.searchType === "partial") {',
    '            current = current.split(entry.originalText).join(entry.changeText);',
    '          } else if (entry.searchType === "regex") {',
    '            const regex = this._getRegex(entry.originalText, entry.flags || "g");',
    '            current = current.replace(regex, entry.changeText);',
    '          }',
    '        }',
    '      }',
    '      if (perf) { perf.translateCalls += 1; perf.translateTime += performance.now() - start; }',
    '      return current;',
    '    }',
    '    translateNode(node) {',
    '      if (!this._enabled) return;',
    '      if (!node || node.nodeType !== Node.TEXT_NODE) return;',
    '      const text = node.textContent;',
    '      if (!text || text.length > 500) return;',
    '      const hash = this._getTextHash(text);',
    '      const prev = this._seenNodes.get(node);',
    '      if (prev === hash) return;',
    '      this._seenNodes.set(node, hash);',
    '      const parent = node.parentElement;',
    '      if (!parent) return;',
    '      const specialRoot = this.findSegmentedTipRoot(parent);',
    '      if (specialRoot) {',
    '        this._translatedSubtrees.delete(specialRoot);',
    '        this.translateSpecialElement(specialRoot);',
    '        return;',
    '      }',
    '      if (this.shouldSkipElement(parent)) return;',
    '      const translated = this.translateTextForElement(text, parent);',
    '      if (translated !== text) {',
    '        this._saveOriginalText(parent, text);',
    '        node.textContent = translated;',
    '      }',
    '    }',
    '    translateExactTextNode(node) {',
    '      if (!this._enabled) return false;',
    '      if (!node || node.nodeType !== Node.TEXT_NODE) return false;',
    '      const text = node.textContent;',
    '      if (!text || text.length > 220) return false;',
    '      const parent = node.parentElement;',
    '      if (!parent || this.shouldSkipElement(parent)) return false;',
    '      let translated = this._exactMap.get(text);',
    '      if (!translated) {',
    '        const compact = text.replace(/\\s+/g, " ").trim();',
    '        if (!compact || compact.length > 220 || compact === text) return false;',
    '        translated = this._exactMap.get(compact);',
    '        if (!translated) return false;',
    '        node.textContent = text.replace(compact, translated);',
    '        return true;',
    '      }',
    '      node.textContent = translated;',
    '      return true;',
    '    }',
    '    translateAttributes(element) {',
    '      if (!this._enabled) return;',
    '      if (!element || element.nodeType !== Node.ELEMENT_NODE) return;',
    '      if (this.shouldSkipElement(element)) return;',
    '      for (const attr of ["title", "aria-label", "aria-description", "placeholder"]) {',
    '        const value = element.getAttribute(attr);',
    '        if (!value) continue;',
    '        const translated = this.translateTextForElement(value, element);',
    '        if (translated !== value) {',
    '          this._saveOriginalAttr(element, attr, value);',
    '          element.setAttribute(attr, translated);',
    '        }',
    '      }',
    '    }',
    '    collectScopeRoots(root) {',
    '      if (!root) return [];',
    '      const results = [];',
    '      const seen = new Set();',
    '      const add = (element) => {',
    '        if (!element || element.nodeType !== Node.ELEMENT_NODE) return;',
    '        if (seen.has(element)) return;',
    '        seen.add(element);',
    '        results.push(element);',
    '      };',
    '      if (root.nodeType === Node.ELEMENT_NODE && this.isScopeContainer(root)) {',
    '        add(root);',
    '      }',
    '      if (!Array.isArray(this.observeScopeSelectors) || this.observeScopeSelectors.length === 0) {',
    '        if (root === document || root === document.documentElement || root === document.body) {',
    '          add(document.body || document.documentElement);',
    '        }',
    '        return results.filter(Boolean);',
    '      }',
    '      if (root.querySelectorAll) {',
    '        try {',
    '          const mergedSelector = this.observeScopeSelectors.join(",");',
    '          const matched = root.querySelectorAll(mergedSelector);',
    '          for (let i = 0; i < matched.length; i++) {',
    '            add(matched[i]);',
    '          }',
    '        } catch {}',
    '      }',
    '      return results.filter(Boolean);',
    '    }',
    '    _chunkedTreeWalk(root, deadline) {',
    '      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, null, false);',
    '      let node;',
    '      while ((node = walker.nextNode())) {',
    '        this.translateNode(node);',
    '        if (deadline && deadline.timeRemaining() <= 2) return false;',
    '      }',
    '      return true;',
    '    }',
    '    _chunkedAttributeWalk(root, deadline) {',
    '      if (root.nodeType === Node.ELEMENT_NODE) {',
    '        this.translateAttributes(root);',
    '      }',
    '      return true;',
    '    }',
    '    runShortExactTextFallback(root) {',
    '      if (!this.shortExactTextFallback || !root || !root.createTreeWalker && !document.createTreeWalker) return;',
    '      const startRoot = root.nodeType === Node.DOCUMENT_NODE ? (root.body || root.documentElement) : root;',
    '      if (!startRoot) return;',
    '      let walker;',
    '      try {',
    '        walker = document.createTreeWalker(startRoot, NodeFilter.SHOW_TEXT, null, false);',
    '      } catch {',
    '        return;',
    '      }',
    '      const schedule = (fn) => {',
    '        if (typeof requestIdleCallback === "function") requestIdleCallback(fn, { timeout: 500 });',
    '        else window.setTimeout(() => fn({ timeRemaining: () => 0 }), 0);',
    '      };',
    '      const process = (deadline) => {',
    '        let node;',
    '        let visited = 0;',
    '        while ((node = walker.nextNode())) {',
    '          this.translateExactTextNode(node);',
    '          visited += 1;',
    '          if (visited >= 400 || (deadline && deadline.timeRemaining && deadline.timeRemaining() <= 2)) {',
    '            schedule(process);',
    '            return;',
    '          }',
    '        }',
    '      };',
    '      schedule(process);',
    '    }',
  ];
}

module.exports = { getClassCoreLines };
